project_name: kubectl-curl
release:
  github:
    owner: michal-kopczynski
    name: kubectl-curl
builds:
- id: "kubectl-curl"
  main: ./cmd/kubectl-curl/main.go
  binary: kubectl-curl
  goos:
    - linux
    - darwin
    - windows
  goarch:
    - amd64
    - arm64
- id: "kubectl-grpcurl"
  main: ./cmd/kubectl-grpcurl/main.go
  binary: kubectl-grpcurl
  goos:
    - linux
    - darwin
    - windows
  goarch:
    - amd64
    - arm64
archives:
- id: "archive"
  name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
  builds:
    - kubectl-curl
    - kubectl-grpcurl
  format: tar.gz
  format_overrides:
    - goos: windows
      format: zip
  files:
    - LICENSE
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
